name: CombatLog
version: '${project.version}'
authors: [Luckdeh, Navoei]
main: me.luckdeh.combatlog.CombatLog
api-version: '1.20'
depend: [PlaceholderAPI]
permissions:
  combatlog.bypass:
    description: Prevents a player from being combat tag and from tagging others.
  combatlog.bypass.timer:
    description: Prevents a player from being combat tagged and from tagging others.
  combatlog.tagcreative:
    description: Allows a player to tag others while in creative mode.
